dist: xenial
language: python
python:
- '3.5'
- '3.6'
- '3.7'
- '3.8'
install:
- pip install -r requirements.txt
script: python -m unittest
deploy:
  provider: pypi
  user: porovozls
  password:
    secure: qaDiANDKVnMRYdp0tXFzqIuZhAWpU5Ae1ksSKlSfrValDgJfHrbRBp8XNlPaT2PZ++GcdP13gIA3jeSu2+YY8Riu1qDgk23Rlx6kaoevIAHHKHKf5Ffu45w9+tDYG3Ujol/RzdEUEFxd9wi9d/rfv/us8jiBGUS+OBADIWW63y/EtY/D13OEkcfhu4OsVAzyM/Wh8hOQB+IhHDgYGEBpSAFG8GKYWShv03velE4rXTDFKETo2W/H1FqIpdn7k01lSggR+ghM6rPMz2NlZFjbPFs8l6CAPlAbLZId6yXLly543SrD0M/6yPO7I9YDzHeHBL+JV8TCZF/QAm5PA55q5GPFaKjdgW2uZcwdwDDfk1dm5OejP8VzmM/IIFYDH4PQlr9cYQB85ZaIq3+2mQMoIGgl/ffLHWGkAF7C4Ljd8qdWSJ9PEZMrJre5+3Q+A1vXBYuBNhHRBxpCD3XNygruwtR1IkVqZ+8ihCeVODWCKPpVa66Qr8pLyFCd8Xxt72RFNj0xvwQKehLK9zRcuu3/ybAW+MpeY6h4lenmAaYe9nmAjEEzTh0YpXZun+ZStFzUrfXcViaNz9Hpm2V3i72W/iHHVb87jxpSGgA3lljD8ayfpXd3JJb7sWiXsDYcxFCc7hg50cjCZrGOmpxzYuVTHGXxkjES+N18Xrrcm1ZOz04=
  on:
    repo: parikls/mem_usage_ui
    python: '3.7'
    tags: true
  skip_cleanup: true
  skip_existing: true
  distributions: sdist
